[book]
authors = ["Chaitanya Joshi"]
language = "en"
multilingual = false
src = "src"
title = "mdBook translate template"

[output.html]
additional-css = ["theme/css/language-picker.css"]
git-repository-url = "https://github.com/joshichaitanya3/mdbook-translate-template"

[preprocessor.gettext]
after = ["links"]
